@host = http://localhost:7071
//@host = https://sql-sat-898-backup.azurewebsites.net

@instance = 8e77ba8feb2e4fddb9e0cb6840f97795
@code = SJe1LZMqTrFK/j0s1kVYD7YfA2R2JOjvAb9IX4G1T8OW5wt5zSqimA==

### Start orchestration
GET {{host}}/api/HttpStart


### Check orchestration status
GET {{host}}/runtime/webhooks/durabletask/instances/{{instance}}
    ?taskHub=TestHubName
    &connection=Storage
    &code={{code}}